# Regression on Sydney Dataset 
### 0. Libraries

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/data.csv')

In [3]:
data

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

### 1. Determine which features are continuous vs categorical. Drop rows without a valid salesprice.
### 2. Visualize the univariate distribution of each continuous feature, and the distribution of thetarget. Do you notice anything? Is there something that might require special treatment?
### 3. Visualize the dependency of the target on each continuous feature (2d scatter plot).
### 4. Split data in training and test set. Do not use the test-set unless for a final evaluation in 2.5.Use ColumnTransformer and pipeline to encode categorical variables (your choice ofOneHotEncoder or another one from the categorical_encoder package, or both). Impute missingvalues using SimpleImputer. Evaluate Linear Regression (OLS), Ridge, Lasso and ElasticNetusing cross-validation with the default parameters. Does scaling the data (within the pipeline)with StandardScaler help? Use the preprocessing that works best going forward.
### 5. Tune the parameters of the models using GridSearchCV. Do the results improve? Visualizethe dependence of the validation score on the parameters for Ridge, Lasso and ElasticNet.
### 6. Visualize the 20 most important coefficients of the resulting models. Do they agree on whichfeatures are important?